server:
  port: 8761
spring:
  application:
    name: szf-eureka-boot
eureka:
  instance:
    hostname: 192.168.154.2
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/